# Example theme in the color format of Alacritty, light side.

[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"

[colors.cursor]
cursor = "#3c3836"

[colors.selection]
background = "#ebdbb2"

[colors.normal]
black = "#fbf1c7"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#3c3836"

[colors.bright]
black = "#928374"
red = "#c14a41"
green = "#96971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#282828"
