[package]
name = "zyt-term"
description = "Stream-agnostic ANSI terminal emulation core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alacritty_terminal.workspace = true
memchr.workspace = true
serde.workspace = true
thiserror.workspace = true
log.workspace = true
