[package]
name = "zyt-keymux"
description = "Context aware key binding manager with command registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_yaml_ng.workspace = true
nucleo-matcher.workspace = true
thiserror.workspace = true
